#!/bin/sh

for IFACE in "$@"; do
    INET=""
    ifconfig $IFACE 2>/dev/null 1>/dev/null && INET=$( ifconfig -f inet:cidr $IFACE inet | grep inet | awk '{print $2}' | tr -d ' ' )
    if [ ! -z $INET6 ] || [ ! -z $INET ]; then
        echo -n "$IFACE "
        if [ ! -z $INET6 ]; then
            echo -n "$INET6 "
        fi
        if [ ! -z $INET ]; then
            echo -n "$INET "
        fi
    fi
done
