#!/bin/sh

IFACE=$1
ifconfig $IFACE 2>/dev/null 1>/dev/null
if [ $? == 0 ]; then
    BSSID=$( ifconfig $IFACE | grep bssid | awk '{print $NF}' )
    SSID=$( ifconfig $IFACE list scan | grep $BSSID | perl -pe 's/^(.*?) +(([0-9a-f]{2}:){5}[0-9a-f]{2}) +.*?$/$1/g' )
    SNR=$( printf "%.2f" `ifconfig $IFACE list scan | grep $BSSID | sed -E 's/.* -([0-9]{2}):-([0-9]{2}) .*/\1\/\2/g' | bc -l | sort -n | tail -n1` )
    echo $SNR $SSID
fi
